name: CI
on:
 workflow_dispatch: 
   inputs: 
     branch: 
       'description': 'To Deploy master'
       'required' : true 
       default: 'main' 
       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository 
      - uses: actions/checkout@v4

      - name: Run a script 
        run: echo "Triggered" 
